import Head from "next/head";
import { Inter } from "@next/font/google";
import Sidebar from "@/components/sidebar/sidebar";
import Feed from "@/components/feed/feed";
import Widgets from "@/components/widgets/widgets";
import { useEffect, useState } from "react";
import CommentModal from "@/components/comment/commentModal";
import Onboarding from "@/components/onboarding/onboarding";
import { themeState } from "atom/userAtom";
import { useRecoilState } from "recoil";
export default function Layout({ newsResults, randomUsersResults, children }) {
  const [themeRecoilState, setThemeRecoilState] = useRecoilState(themeState);
  const [theme, setTheme] = useState(themeRecoilState ? "dark" : "light");

  useEffect(() => {
    setTheme(themeRecoilState ? "dark" : "light");
  }, [themeRecoilState]);

  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.freepnglogos.com/uploads/twitter-logo-png/twitter-logo-vector-png-clipart-1.png"
        />
      </Head>
      <main className={`${theme} flex min-h-screen mx-auto`}>
        {/* Sidebar */}
        <Sidebar
          setThemeRecoilState={setThemeRecoilState}
          themeRecoilState={themeRecoilState}
        />
        {/* Feeds */}
        {/* <Feed /> */}
        {children}
        {/* Widgets */}
        <Widgets
          newsResults={newsResults}
          randomUsersResults={randomUsersResults}
        />
        {/* Modal */}
        <CommentModal theme={theme} />
        <Onboarding theme={theme} />
      </main>
    </>
  );
}
